name: Push Event Workflow

on: push

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Package
      run: pip install flake8
      
    - name: Run tests
i191715_test
      run: flake8 knowledge_gpt/embeddings.py
      run: flake8 knowledge_gpt/utils.py
main
